### ISSUE TITLE
is there any plan to automate data update?

### ISSUE THREAD

**Issue by statkclee** [RamiKrispin/coronavirus#1]
This is a really great data package... but do you have any plan to update dataset automatically?

**Comment by javierluraschi** [comment]
Not a covid-10 expert here, but put together an automated pipeline directly from the WHO reports.

Since it's parsed from the PDFs, one would need to clean this datasets a bit more. The challenge is that the reports seem to be changing daily so the parsing rules that worked yesterday, might not work today. In any case, if someone wants to build on top of this, the repo is here: https://github.com/javierluraschi/covid

Therefore, the manual approach to update a tidy dataset is probably more reliable for now.

**Comment by RamiKrispin** [comment]
@statkclee yes, my plan is to run a cron job on a raspberry pi to automate the process, hopefully, this weekend.

**Comment by RamiKrispin** [comment]
@javierluraschi that is an awesome approach!

**Comment by statkclee** [comment]
@javierluraschi @RamiKrispin Thank you... I am developing a prototype for this semester as a studuent dashboard tutorial; [corona dashboard](https://statkclee.github.io/comp_document/cd-corona.html), [dashboard tutorial](https://statkclee.github.io/comp_document/cd-dashboard.html). 

This is a sort of initial dry-run such that it's not good enough. I have a plan to update this dashboard and tutorial with realtime support feature. 

Please let me know when you build data pipeline.

**Comment by statkclee** [comment]
@RamiKrispin Excellent!!! 
Time series data should be plotted with Highchart... Agreed!!!

**Comment by piccolbo** [comment]
I built a visualization here https://piccolbo.shinyapps.io/covid-19/ Not a dashboard, just one possible stats graphics. Thanks for your work, I hope it stays up-to-date. Let me know if I can help

**Comment by RamiKrispin** [comment]
@piccolbo awesome plot! hope you are going to add more functionality :)

**Comment by piccolbo** [comment]
Thanks. I don't see any updates since yesterday, is it my app or is the backend not working nightly? As to features please open an issue here https://github.com/piccolbo/covid-19

**Comment by piccolbo** [comment]
Oh I see. I misunderstood how dynamic this thing was. I need to re-download the package. On it.

**Comment by piccolbo** [comment]
Since I can't update the package from inside a shiny app hosted on shinyapps.io, I am now fetching the data directly from github in  master. Just FYI, shouldn't be a problem unless you change column names or types.

**Comment by connorcodes** [comment]
> @javierluraschi @RamiKrispin Thank you... I am developing a prototype for this semester as a studuent dashboard tutorial; [corona dashboard](https://statkclee.github.io/comp_document/cd-corona.html), [dashboard tutorial](https://statkclee.github.io/comp_document/cd-dashboard.html).
> 
> This is a sort of initial dry-run such that it's not good enough. I have a plan to update this dashboard and tutorial with realtime support feature.
> 
> Please let me know when you build data pipeline.

I am also building a dashboard over on Observable. 

I’m planning to use live data OR multiple sources and live updating numbers send which dataset was most recent. I’m hoping to do a graph, map, and bar-chase just like yours.

The end goal is to run the dashboard on my raspberry pi and have it on a monitor as a little status screen next to my desk.

**Comment by jebyrnes** [comment]
It ain't perfect, but, see https://github.com/RamiKrispin/coronavirus/pull/8 (and/or my fork) for an update method.

**Comment by jimmyd7377** [comment]
Hello, first-time git hubber lol full time Bi-onear. Im looking to create some dashboards from this dataset. i''m using https://github.com/javierluraschi/covid as the repo details but I'm being asked for a owner i have put javierluraschi but I'm being told that I do not have access.

any tips?

Kindest Regards 

Jimmy

**Comment by piccolbo** [comment]
You need to report this as an issue in that repo you are pointing too.

**Comment by RamiKrispin** [comment]
The data is now updated with cron job
