### ISSUE TITLE
0 Case Vectors (non-essential)

### ISSUE THREAD

**Issue by j4yr0u93** [RamiKrispin/coronavirus#10]
Is there any easy way to generate/insert a vector for each location and date that report 0 occurences of each type when there is no report? 

This is probably my problem more than anybody's but doing any kind of data animation with ggplot or looking at cumulative sums gets really messy without having 0 case vectors.

**Comment by piccolbo** [comment]
I use a pivot wider with a fill argument followed by a pivot_longer from tidyr, code is my repo @piccolbo/covid-19

**Comment by RamiKrispin** [comment]
@j4yr0u93 the updated version (as of yesterday) is filed with 0 when no new cases where found. So for each country or province (when applicable), you should have a sequential data starting from Jan 22.
