### ISSUE TITLE
Automatic update unsuccessful on Jan 13 2022

### ISSUE THREAD

**Issue by stepminer** [RamiKrispin/coronavirus#107]
Greetings Rami,
I run devtools::install_github("RamiKrispin/coronavirus", force = TRUE)
as usual on Jan 13,  3:21 ET. The download successfully completed.
However, The data has not changed. I am still getting the same values as of Jan 12, 2022.
I tried several downloads. same issue.

Any hints on why this is happening and how to fix the issue?

Best

**Comment by RamiKrispin** [comment]
Yes, I see the pipeline is working but the data is not refreshed, checking...

**Comment by RamiKrispin** [comment]
Check it, there was no issue with the data pipeline on my end, it might be that the data refresh was delayed on JHU. Below the is the pipeline log:

``` r
                  time         dataset  nrows  last_date update success branch
325 2022-01-13 08:23:41     coronavirus 595650 2022-01-12   TRUE    TRUE master
326 2022-01-13 08:24:12 covid19_vaccine 146433 2022-01-12   TRUE    TRUE master
327 2022-01-13 16:49:51     coronavirus 595650 2022-01-12  FALSE    TRUE master
328 2022-01-13 16:50:00 covid19_vaccine 146433 2022-01-12  FALSE    TRUE master
329 2022-01-14 00:17:45     coronavirus 596475 2022-01-13   TRUE    TRUE master
330 2022-01-14 00:18:07 covid19_vaccine 146433 2022-01-12  FALSE    TRUE master
331 2022-01-14 08:18:27     coronavirus 596475 2022-01-13  FALSE    TRUE master
332 2022-01-14 08:18:42 covid19_vaccine 147134 2022-01-13   TRUE    TRUE master
333 2022-01-14 16:47:00     coronavirus 596475 2022-01-13  FALSE    TRUE master
334 2022-01-14 16:47:11 covid19_vaccine 147134 2022-01-13  FALSE    TRUE master
```

* The `success` field indicates if the pipeline unit tests passed (`TRUE`) or failed (`FALSE`)
* The `update` field indicates that there was new data whenever it return `TRUE`
* The `last_date` indicates what is the most recent date in the dataset. 

As you can see the data is up-to-date to Jan 13, as expected (one day delay). I will track it in the coming days to make sure there is no issue with the package data pipeline.

**Comment by RamiKrispin** [comment]
You can see the output of the data refresh over here:
https://ramikrispin.github.io/coronavirus/data_pipelines/covid19_cases.html

**Comment by ondohotola** [comment]
I am getting similar issues sine a few days

```
> devtools::install_github("RamiKrispin/coronavirus")
Downloading GitHub repo RamiKrispin/coronavirus@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  :
  download from 'https://api.github.com/repos/RamiKrispin/coronavirus/tarball/HEAD' failed
```

**Comment by RamiKrispin** [comment]
Working on my end. Could you please try to remove and reinstall it? 

Also, you can install it from CRAN and run the `coronavirus::update_dataset()` function to update your local package or use `coronavirus::refresh_coronavirus_jhu()` function to get the most recent dataset from Github.
