### ISSUE TITLE
About Recovered Cases

### ISSUE THREAD

**Issue by wakibia** [RamiKrispin/coronavirus#108]
Hi there
I just wanted to bring to your attention that for the type variable there are no recovered cases rather there is recovery.

**Comment by RamiKrispin** [comment]
Hi @wakibia,

I am using the terminology as used on the raw data, please see:

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv

**Comment by wakibia** [comment]
Noted
