### ISSUE TITLE
Country name in standard format

### ISSUE THREAD

**Issue by shubhrampandey** [RamiKrispin/coronavirus#11]
Hi, 

Could you please name the country in a standard format because when I am plotting this data in a spatial map then some of the countries data is not plotted for eg. Iran because in your dataset Iran is named as Iran(Islamic Republic of)

Thanks

**Comment by piccolbo** [comment]
I am also user of this package so I can try to answer. This package is using any names used in the  data sources. Not easy to reconcile with standard names, whatever standard you are referring to. What is the standard name for Mainland China or Taiwan? You could try to build a translation layer to the standard you want to comply with, but it would introduce error. Just my opinion

**Comment by jebyrnes** [comment]
Try
```
library(coronavirus)
library(sf)
library(rnaturalearth)
library(dplyr)

worldmap <- ne_countries(returnclass="sf") %>%
  rename(status = type)

coronavirus_sf <- coronavirus %>%
  st_as_sf(coords = c(x = "Long", y = "Lat"),
           crs = st_crs(worldmap)) %>%
  st_join(worldmap)
```

This introduces many new columns with standard names and other administrative info.

**Comment by piccolbo** [comment]
It detects everything as country.

```
coronavirus_sf %>% filter(grepl(pattern = "Washington.*", x = Province.State))
```

**Comment by jebyrnes** [comment]
Yes! `ne_countries()` is just for countries. For states in the US, you can do something like

```
usa <- ne_states(country = "United States of America", returnclass = "sf")

#make some spatial objects
usa_coronavirus_sf <- coronavirus %>%
  filter(Country.Region=="US") %>%
  st_as_sf(coords = c(x = "Long", y = "Lat"),
           crs = st_crs(usa)) %>%
 st_join(usa)
```

If you don't supply any argument to `ne_states()` it returns many countries with the admin column (I think) as country - maybe that's a better solution for the long-term?

**Comment by piccolbo** [comment]
Tried your snippet but it fails on installing rnaturalearthhires `install.packages("rnaturalearthhires", repos = "http://packages.ropensci.org", type = "source")` returns "error reading from connection". Can reach in the browser. Is that how you installed it?

**Comment by jebyrnes** [comment]
Odd.

try
```
devtools::install_github("ropensci/rnaturalearthhires")
```

**Comment by piccolbo** [comment]
Still wrong, all washington counties reported as states.  I think I am satisfied this is not reliable enough for my needs but thanks.

**Comment by jebyrnes** [comment]
Which column are you looking at?

**Comment by RamiKrispin** [comment]
Hi @shubhrampandey, currently I am using the raw data countries labels, which keep changing on a daily bases (e.g., Iran was changed to Iran(Islamic Republic of)). @jebyrnes added function to plot the data on maps. I will make the modification in the countries labels if needed, that it will work with the standard spatial mapping labels

**Comment by jebyrnes** [comment]
Oh - you want counties, not states! Sorry, @piccolbo! Misunderstood. For that, you'll want to use `tidycensus` and `tigris` 

For example
```
#counties
library(tigris)
wa_county_maps <- st_as_sf(counties(state="Washington",  cb=TRUE)) %>%
  st_transform(st_crs(usa_confirmed_sf))

wa_counties_coronavirus <- st_join(wa_county_maps, usa_confirmed_sf) %>%
  filter(!is.na(STATEFP)) %>%
  group_by(NAME, STATEFP) %>%
  summarize(total_cases = sum(cases))

ggplot(wa_county_maps) +
  geom_sf(fill = "white") +
  geom_sf(data = wa_counties_coronavirus, mapping = aes(fill = total_cases)) +
  scale_fill_viridis_c(na.value = "white") +
  theme_minimal()
```

![image](https://user-images.githubusercontent.com/757410/76567714-be0a5e80-6485-11ea-9917-a37dd03853ba.png)


There are other packages out there with similar map info - `maps`, `USAboundaries`, `urbanmapr' (on github) are all nice ones. If you're newer to spatial joins and geospatial work, I highly recommend https://geocompr.robinlovelace.net/

Here's one example. Again, I'm using counties generated by matching lat/longs with the geospatial package rather than using the ones from the data itself

```
library(urbnmapr)

counties_sf <- get_urbn_map("counties", sf = TRUE) %>%
  st_transform(st_crs(usa_confirmed_sf)) %>% #match projections
  filter(!(state_name %in% c("Alaska", "Hawaii"))) #puts them in a funny place for st_join
  
counties_coronavirus <- st_join(counties_sf, usa_confirmed_sf) %>%
  filter(!is.na(county_name)) %>%
  group_by(county_fips, county_name, state_name) %>%
  summarize(total_cases = sum(cases))

ggplot(counties_sf) +
  geom_sf(fill = "white", alpha= 0.2) +
  geom_sf(data = counties_coronavirus, mapping = aes(fill = total_cases),
          color = NA) +
  scale_fill_viridis_c(na.value = "white") +
  theme_minimal()
```

![image](https://user-images.githubusercontent.com/757410/76569096-b00a0d00-6488-11ea-82df-6408c70c9d02.png)

**Comment by jebyrnes** [comment]
You can use this general workflow to do it by census tract even

```
#ma by acs
library(tidycensus)

ma_tract <- get_acs(state = "MA",  geography = "tract", variables = "B19013_001",
                    geometry = TRUE) 

ma_tract_tr <- ma_tract %>%
  select(-variable, -estimate) %>%
  st_transform(st_crs(usa_confirmed_sf))

ma_tract_coronavirus <- st_join(ma_tract_tr, usa_confirmed_sf) %>%
  filter(!is.na(NAME)) %>%
  group_by(NAME, GEOID) %>%
  summarize(total_cases = sum(cases))

ggplot(ma_tract_coronavirus) +
  geom_sf(fill = "white", alpha= 0.2) +
  geom_sf(data = ma_tract_coronavirus, mapping = aes(fill = total_cases), color = NA) +
  scale_fill_viridis_c(na.value = "white") +
  theme_minimal()
```

![image](https://user-images.githubusercontent.com/757410/76569732-3541f180-648a-11ea-91e1-c4f19fb65db8.png)

**Comment by piccolbo** [comment]
Sorry @jebyrnes I really can't get through. I decided to pull my own data. No worries. Thanks for your patience.
