### ISSUE TITLE
coronavirus_2023.csv is not being updated

### ISSUE THREAD

**Issue by valmetisrinivas** [RamiKrispin/coronavirus#115]
It looks like the file [coronavirus_2023.csv](https://github.com/RamiKrispin/coronavirus/blob/main/csv/coronavirus_2023.csv) is not being updated for almost a week now. Appreciate someone looks into this. Thank you.

**Comment by RamiKrispin** [comment]
Thanks @valmetisrinivas, checking it.

**Comment by RamiKrispin** [comment]
Apparently, John Hopkins University stopped the data collection last week, therefore, the data on the package stopped getting updated. Unfortunately, as this package is a wrapper of the John Hopkins dataset, it won't get updates moving forward.

**Comment by RamiKrispin** [comment]
Here is the update on project README:
https://github.com/CSSEGISandData/COVID-19#covid-19-data-repository-by-the-center-for-systems-science-and-engineering-csse-at-johns-hopkins-university

**Comment by valmetisrinivas** [comment]
Thanks a lot Rami. It was wonderful using the dataset.
