### ISSUE TITLE
Error in Hubei data for 3/11/2020

### ISSUE THREAD

**Issue by tcarleton** [RamiKrispin/coronavirus#12]
Hi,

It looks like there's an error in your dataset for the confirmed cases entry for Hubei for 3/11/2020 -- the total cumulative cases are listed (67773) instead of the new cases for that day (13), although all other entries for other location-days appear to be reporting new cases for that day (based on comparing with the raw .csv's from Johns Hopkins).

Thanks for the package!

**Comment by RamiKrispin** [comment]
Checked the data, it seems that it aligned with the raw data of John Hopkins [csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv):
Here are the number of confirmed cumulative cases in John Hopkins from the last 3 days (March 10-12):
```
67760 | 67773 | 67781
```
Hence on March 11th and 12th there were 13 and 8 new cases respectively.

Here is the output from the `coronavirus` dataset:

```
coronavirus %>% dplyr::filter(Province.State == "Hubei", date >= max(date) - lubridate::days(1), type == "confirmed")
  Province.State Country.Region     Lat     Long       date cases      type
1          Hubei          China 30.9756 112.2707 2020-03-11    13 confirmed
2          Hubei          China 30.9756 112.2707 2020-03-12     8 confirmed
```

**Comment by tcarleton** [comment]
Thanks, you're right, totally checks out.

Not sure if you updated something or not but the same code gave me 67773 for 2020-03-11 for Hubei yesterday -- all checks out now.
