### ISSUE TITLE
Error when devtools::install_github("RamiKrispin/coronavirus")

### ISSUE THREAD

**Issue by Danielchui** [RamiKrispin/coronavirus#13]
install.packages("devtools")
devtools::install_github("RamiKrispin/coronavirus")

Error message:
Installing package into ‘/databricks/spark/R/lib’ Error : Failed to install 'coronavirus' from GitHub:
  (converted from warning) installation of package ‘units’ had non-zero exit status.

**Comment by RamiKrispin** [comment]
I am not sure what is causing this error. I can guess that one of the package dependencies are not installed. Try to install the following packages:
tidyr, purrr,  dplyr,  rnaturalearth,  sf,

and see if any of those causing the error.
