### ISSUE TITLE
Connecting through Power BI

### ISSUE THREAD

**Issue by jimmyd7377** [RamiKrispin/coronavirus#14]
Hello, first-time git hubber lol full time Bi-onear. Im looking to create some dashboards from this dataset. i''m using https://github.com/javierluraschi/covid as the repo details but I'm being asked for a owner i have put javierluraschi but I'm being told that I do not have access.
any tips?
Kindest Regards
Jimmy

**Comment by RamiKrispin** [comment]
I suggest opening an issue on repo that you are using for the data, which in this case is  https://github.com/javierluraschi/covid. I cannot answer on behalf of javierluraschi
