### ISSUE TITLE
Some impossible data

### ISSUE THREAD

**Issue by stainesa** [RamiKrispin/coronavirus#15]
Hi,
There are 19 records with negative case numbers?
Regards,
Anthony
# A tibble: 19 x 7
   Province.State          Country.Region   Lat  Long date       cases type     
   <chr>                   <chr>          <dbl> <dbl> <date>     <int> <chr>    
 1 ""                      Japan           36   138   2020-02-07   -20 confirmed
 2 ""                      Korea, South    36   128   2020-03-08   -17 recovered
 3 "Diamond Princess"      Cruise Ship     35.4 140.  2020-03-06   -10 confirmed
 4 "From Diamond Princess" Australia       35.4 140.  2020-02-29    -8 confirmed
 5 "Hainan"                China           19.2 110.  2020-02-15    -4 recovered
 6 "Guizhou"               China           26.8 107.  2020-02-06    -3 recovered
 7 "Saint Barthelemy"      France          17.9 -62.8 2020-03-09    -2 confirmed
 8 "Washington, D.C."      US              38.9 -77.0 2020-03-10    -2 confirmed
 9 "Heilongjiang"          China           47.9 128.  2020-02-11    -2 recovered
10 "Ningxia"               China           37.3 106.  2020-02-09    -2 recovered
11 ""                      Japan           36   138   2020-01-23    -1 confirmed
12 "Northern Territory"    Australia      -12.5 131.  2020-03-06    -1 confirmed
13 "Queensland"            Australia      -28.0 153.  2020-01-31    -1 confirmed
14 "Queensland"            Australia      -28.0 153.  2020-02-02    -1 confirmed
15 ""                      Italy           43    12   2020-02-24    -1 recovered
16 "Diamond Princess"      Cruise Ship     35.4 140.  2020-02-23    -1 recovered
17 "Guangxi"               China           23.8 109.  2020-02-12    -1 recovered
18 "Hong Kong"             China           22.3 114.  2020-02-21    -1 recovered
19 "Shanxi"                China           37.6 112.  2020-02-03    -1 recovered
>

**Comment by RamiKrispin** [comment]
Hi Anthony

Negative values can appear on the data when the cumulative cases were decreased on a given day (with respect to the previous one). This could occur when some cases removed or modified for a variety of reasons (false positive, bad classification, typos, etc.)

Please see respond of John Hopkins for the following [issue](https://github.com/CSSEGISandData/COVID-19/issues/285)

Best,
Rami

**Comment by stainesa** [comment]
Thanks!
