### ISSUE TITLE
Seems that the data is not up to date

### ISSUE THREAD

**Issue by lilywang1988** [RamiKrispin/coronavirus#16]
Hi Rami,

Thank you for the excellent work! I installed the package today and found that if I use the tail() it gave me the output below, which implies that the data was not updated to today. Could you help me figure out the reason? Hope it would not take you much time. Not sure whether other users have the same problem.  Thank you in advance!

![image](https://user-images.githubusercontent.com/11320575/76685044-08efb780-65e7-11ea-8934-a553dd0d4d66.png)

Best,
Lili

**Comment by RamiKrispin** [comment]
Hi @lilywang1988 

You are using the CRAN version which is up-to-date till Feb 16. To get the most update versionyou need to install the Github version using the following:
```
# install.packages("devtools") 
devtools::install_github("RamiKrispin/coronavirus")
```

Best,
Rami

**Comment by lilywang1988** [comment]
Hi Rami,

Thank you a lot! The problem has been solved. 

Best,
Lili
