### ISSUE TITLE
Data not updated

### ISSUE THREAD

**Issue by shubhrampandey** [RamiKrispin/coronavirus#21]
Hi Rami,

Thanks for the excellent work. It seems that data is not being updated since last two days.

Thanks
Shubhram

**Comment by RamiKrispin** [comment]
Hi @shubhrampandey 

The data is been updated on a daily bases, you can track the updates over [here](https://github.com/RamiKrispin/coronavirus/commits/master/data). The `covid_italy` data is going to be removed from the package and be available on a new package [covid19italy](https://github.com/RamiKrispin/covid19Italy)

Is there a specific dataset that is not updated?

Note that

**Comment by gexijin** [comment]
Hi Rami, 
Can we keep the Italy data in both places? 
Also do we need to re-install the packages to update the data? 
Thanks!

**Comment by RamiKrispin** [comment]
Discussed offline, issue solved
