### ISSUE TITLE
Iran Dataset not in the correct location

### ISSUE THREAD

**Issue by KenneySnell** [RamiKrispin/coronavirus#23]
I made these changes to reading in df4

  # Update the Iran dataset
  df4 <- read.csv(file = "https://raw.githubusercontent.com/RamiKrispin/coronavirus-csv/master/iran/covid_iran_long.csv", stringsAsFactors = FALSE)
#  df4 <- read.csv(file = "https://github.com/RamiKrispin/coronavirus-csv/blob/master/iran/covid_iran_long.csv", stringsAsFactors = FALSE)

**Comment by RamiKrispin** [comment]
Thanks @KenneySnell 
I made some [changes](https://github.com/RamiKrispin/coronavirus/commit/12c5e500aff0b5f7d86e8d22a56c17f53c05135d#diff-eafbf7d27bcc9e997772628c06a0480f) to this function, that should work now.

**Comment by RamiKrispin** [comment]
I think you can use either:
1. use the `update_datasets` function. This function checks if there is any new data in the dev version and install it from github, or
2. Read the csv files from the repo 
I would create some cron job to automate this process (unless the shiny app can load on the fly the csv files)

**Comment by KenneySnell** [comment]
Rami

Thanks again for your response.  

Last night I ran the update_datasets and it worked - no updates added after I reinstalled the Dev Coronavirus package. 

This is what I expected; but wanted to get your updated code on the update_datasets function.  I  saw that you took out Italy csv from the function.  

Is the purpose for the subset datasets like Iran or South Korea to get updates down to city level or something else?

Where do I find the data on the city level for US or other countries?

Thank you 

Kenney

**Comment by RamiKrispin** [comment]
Hi Kenney, 

Happy to hear it works.  Italy data was removed from the package and moved to a new package [**covid19italy**](https://github.com/RamiKrispin/covid19Italy) which has more granular data about Italy. Similarly, after installing from CRAN you can use the update_datasets to update the datasets. 

Adding more data is depend on the availability of data resources. The following [issue](https://github.com/RamiKrispin/coronavirus/issues/30) describes this effort. If you find a valid data resource (from accessibility to the data and license) please feel free to add it to that issue.

Best,
Rami
