### ISSUE TITLE
An idea for 0.3 - making data retrieval flexible.

### ISSUE THREAD

**Issue by jebyrnes** [RamiKrispin/coronavirus#24]
As I look at the infrastructure so far, and where the whole coronavirus data retrieval and sharing effort is going, I had a thought. I'm curious what you think, @RamiKrispin and other users.

So, thus far, we've added two additional data sets. My contribution for 0.2 has been spatial (more on that in another issue) and adding the coronadatascraper data, as well as providing `update_coronavirus_raw()` and `update_coronavirus_cds_raw()`. The `update_datasets()` function works well to pull from QC-ed (as it were) data from a single source, and doesn't require the reprocessing of the raw scripts.

I'm noticing, though, as more datasets are added, the size of the package grows larger, such that it is generating warnings. This is only going to get worse as more data accumulated.

This has made me think. A lot. Particularly about many good ropensci packages - I use https://github.com/ropensci/rnoaa a lot for work. These packages provide an architecture to allow people to get big NOAA data sets. Sometimes pre-filtered (they use a database to hold them all), but, at least the data doesn't live with the package (except for some small demo datasets).  So, I was wondering, after the dust clears and 0.2 is on CRAN, as we work to 0.3, should we rethink our architecture a bit. Consider the following proposal.

1. We really try and make this package the big aggregator of all SARS-Cov-2 datasets out there.

2. The datasets are hosted, after processing, on github, and updated daily (this could be more frequent with a different hosting plan - might be worth contacting @ropensci to see how they do it) (or working with them - I have contacts!).

3. The package has three main functions:
       -  `get_coronavirus_data_info()` - this returns a data frame of the name of the data sets, a brief description, and link to the source.
       -  `get_coronavirus_data(dataset = "JHU")` JHU is the default. This pulls one of the datasets listed in the above function from the QC-ed source from #2 above.
       -  `get_coronavirus_data_raw(dataset = "JHU") JHU as the default again. This calls one of our update_raw scripts that pulls the data from its source, so that users who want to get the freshest data can do so. But, we include a warning about the possible issues of doing so (datasets are in flux, etc.)

4.  `get_coronavirus_data()` can return a tibble or a sf object, when possible. OR - and this is radical - we could have a column of options of different returntypes for each dataset in `get_coronavirus_data_info()`. This gives us the flexibility of handling most any dataset that comes our way

5. Each dataset gets a vignette with all of the requisite metadata and a simple example.

Thoughts?

**Comment by jebyrnes** [comment]
Could also start a separate issue on datasets to add - e.g. the EcDC dataset https://kieranhealy.org/blog/archives/2020/03/21/covid-19-tracking/

**Comment by RamiKrispin** [comment]
@jebyrnes  that sounds great, I need to div deeper and learn how does it works and what are the required dependencies

**Comment by RamiKrispin** [comment]
Tasked moved to the [Covid19R](https://github.com/Covid19R)
