### ISSUE TITLE
Pkg is GREAT but update_datasets() Fx gives error in Rstudio.

### ISSUE THREAD

**Issue by sfd99** [RamiKrispin/coronavirus#25]
Hi Rami,
Great and critically IMPORTANT pkg!!.
Installed _the CRAN version_.

**_Q:_**
Trying to update 
to the latest version of the **Coronavirus** dataset 
with Fx: 
    > update_datasets()
but get:
  Error in update_datasets() : could not find function "update_datasets"

Help, Rami! 
Am I using the wrong function syntax?.
How can I easily update to the latest **Coronavirus** dataset?.
Thanks 10^6 !!

**SFd99
San Francisco.
latest Rstudio and R / Ubuntu Linux 18.04 64bits**

**Comment by RamiKrispin** [comment]
Hi @sfd99, yes that would not work as this function is not yet pushed to CRAN. Please install the dev version from Github using the following:
```
devtools::install_github("RamiKrispin/coronavirus")
```

And moving forward you can use `update_datasets()` to update the data.

Working on pushing this update to CRAN, possibly next week.

Best,
Rami

**Comment by sfd99** [comment]
Thanks Rami!.
UNinstalled the CRAN version and tried:

> devtools::install_github("RamiKrispin/coronavirus")

but get this install error:
*(sorry for the long message text...)*

*Downloading GitHub repo RamiKrispin/coronavirus@master
Installing 6 packages: rnaturalearth, sf, classInt, units, e1071, sp
Installing packages into ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/rnaturalearth_0.1.0.tar.gz
<https://cloud.r-project.org/src/contrib/rnaturalearth_0.1.0.tar.gz>'
Content type 'application/x-gzip' length 193162 bytes (188 KB)
==================================================
downloaded 188 KB

trying URL 'https://cloud.r-project.org/src/contrib/sf_0.8-1.tar.gz
<https://cloud.r-project.org/src/contrib/sf_0.8-1.tar.gz>'
Content type 'application/x-gzip' length 8469173 bytes (8.1 MB)
==================================================
downloaded 8.1 MB

trying URL 'https://cloud.r-project.org/src/contrib/classInt_0.4-2.tar.gz
<https://cloud.r-project.org/src/contrib/classInt_0.4-2.tar.gz>'
Content type 'application/x-gzip' length 22054 bytes (21 KB)
==================================================
downloaded 21 KB

trying URL 'https://cloud.r-project.org/src/contrib/units_0.6-6.tar.gz
<https://cloud.r-project.org/src/contrib/units_0.6-6.tar.gz>'
Content type 'application/x-gzip' length 959116 bytes (936 KB)
==================================================
downloaded 936 KB

trying URL 'https://cloud.r-project.org/src/contrib/e1071_1.7-3.tar.gz
<https://cloud.r-project.org/src/contrib/e1071_1.7-3.tar.gz>'
Content type 'application/x-gzip' length 582517 bytes (568 KB)
==================================================
downloaded 568 KB

trying URL 'https://cloud.r-project.org/src/contrib/sp_1.4-1.tar.gz
<https://cloud.r-project.org/src/contrib/sp_1.4-1.tar.gz>'
Content type 'application/x-gzip' length 1132945 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

* installing *source* package ‘units’ ...
** package ‘units’ successfully unpacked and MD5 sums checked
** using staged installation
configure: units: 0.6-6
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++11 accepts -g... yes
checking how to run the C++ preprocessor... g++ -std=gnu++11 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for error_at_line... yes
checking for gcc... gcc -std=gnu99
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking for XML_ParserCreate in -lexpat... no
checking udunits2.h usability... no
checking udunits2.h presence... no
checking for udunits2.h... no
checking udunits2/udunits2.h usability... no
checking udunits2/udunits2.h presence... no
checking for udunits2/udunits2.h... no
checking for ut_read_xml in -ludunits2... no
configure: error: in `/tmp/RtmpgiPEoR/R.INSTALL25cf731336b2/units':
configure: error:
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/units’
Error: Failed to install 'coronavirus' from GitHub:
  (converted from warning) installation of package ‘units’ had
non-zero exit status
*

*Help, Rami!.*
*Normally, I have no problem installing pkgs...*

RAY
*calintel*@gmail.com
San Francisco.
---

**Comment by RamiKrispin** [comment]
Can you try to install separately each one of the following packages:
- tidyr
- purrr
- dplyr
- rnaturalearth
 - sf

And see if any of those packages are causing the error?

**Comment by sfd99** [comment]
*Hi Rami,*

As the installation error messages suggested,
I installed in *Ubuntu Linux 18.04* Terminal:
        libudunits2-dev
 with: $ sudo apt-get install libudunits2-dev

That linux file install went *fine*.
---
Then, installed with *NO problem*:

   - *tidyr*
   - *purrr*
   - *dplyr*
   - *units*

*but...*when trying to install either:
   * rnaturalearth **or* the* sf *package
*(in any order)*, I always get these mssgs:

Warning in install.packages :
   installation of package ‘*rnaturalearth*’ had non-zero exit status
*or also*:
Warning in install.packages :
    installation of package ‘*sf*’ had non-zero exit status

There's a kind of "mean / nasty" dependency
btw both pkgs:
*      rnaturalearth  **and**  sf.*

Maybe I'm missing another 3rd pkg,
which both need?.

RAY
*calintel*@gmail.com
 machine learning and AI
 data research, analysis & interpretation
 web technology & solutions
---

**Comment by sfd99** [comment]
OK - some good news.

To install the coronavirus from Github,
in Linux Ubuntu 18.04 64bits
via devtools, this is what I did:
(in case it helps others...)

sudo apt-get install libudunits2-dev
sudo apt install libgdal-dev

then these R pkgs all installed ok:
tidyr
purrr
dplyr
units
rnaturalearth
sf

Then Install:
  devtools::install_github("RamiKrispin/coronavirus")
YAY! INSTALLED OK!

But... when I try:
 update_datasets()
or any other Function in the coronavirus pkg,
in the Rstudio Vignette , I get:

Error in fetch(key) : lazy-load database
'/home/ray/R/x86_64-pc-linux-gnu-library/3.6/coronavirus/help/coronavirus.rdb'
is corrupt

Oh, man!
 ...we are *so close* - we are *almost* there :-)

RAY
*calintel*@gmail.com
San Francisco/
---

**Comment by RamiKrispin** [comment]
I think you are getting these errors as some of the R's compiler are not installed. I will try to run in a docker container to identify if this is the case

**Comment by sfd99** [comment]
Ah, understood Rami.

I do have the latest version of R (3.6.3)
and the latest Rstudio 
f/ Ubuntu Linux 18.04, 64bits.

Maybe the gcc pkg has been updated recently?...
Sometimes, pkg updates will break things!.

btw: 
 all other R pkgs install normally in my Rstudio.

Thanks, Rami!.

**Comment by RamiKrispin** [comment]
Went over the error log again, and I think that the error is because you are missing the following compiler:
libudunits2-dev

Can you please try to run `sudo apt-get install -y libudunits2-dev` and repeat the installation?

**Comment by sfd99** [comment]
_Ah, yes,_
Run (as you suggested):
 sudo apt-get install -y libudunits2-dev
in Ubuntu 18.04.

Now, the coronavirus pkg
installed f/ GIThub, w/o any problems!.

Anyhow, will wait
for your update of the next **CRAN** stable version.

Thanks for all the help, Rami!.
You are indeed doing a great,  important job.
-----------

**Comment by RamiKrispin** [comment]
Thanks! happy we could solve this issue :)
