### ISSUE TITLE
Separate update and data access into different packages? 0.3 thought.

### ISSUE THREAD

**Issue by jebyrnes** [RamiKrispin/coronavirus#26]
One thing that occurs to me is that, as we move forward, to rectify issues in different datasets, we have to do a lot of reprocessing. While some folk might want the latest data scrapped directly from a site, adding update raw scripts has upped the number of dependencies a great deal. If in 0.3 we move to more access to a broad array of data sets, as mentioned in https://github.com/RamiKrispin/coronavirus/issues/24 then perhaps it would be worth splitting the raw update scripts into a separate package to lower the dependencies? Just a thought. Curious what you think.

**Comment by RamiKrispin** [comment]
Tasked moved to the [Covid19R](https://github.com/Covid19R)
