### ISSUE TITLE
Adding a country filter to the dashboard

### ISSUE THREAD

**Issue by Agusum** [RamiKrispin/coronavirus#3]
Congrats on this visualization, it's the best I've seen!

Will it be possible to add a country filter to the dashboard in the Summary and Trends tab?

I want to see how fast the virus is spreading daily through certain European countries and it's not currently possible as the data is only aggregated.

**Comment by RamiKrispin** [comment]
Thanks @Agusum! Unfortunately, in the current setting (github page), it is not possible to add filters as it required a server. I might create a shiny version and try to deploy it

**Comment by Agusum** [comment]
That'll be amazing. Looking forward to it!

**Comment by dskov** [comment]
I added an easy filter. It is required to make a copy of dset. Here is the code:

data("coronavirus")

# Select country list
#country_list <- c("Italy", "France", "Germany", "UK", "Switzerland", "Norway")
#country_list <- c("Mainland China")
#country_list <- c("US")
country_list <- c("Italy")


# Negate logical operator
`%notin%` <- Negate(`%in%`)

# Apply Filter
justSelReg <- coronavirus  %>%
  dplyr::mutate(sel_region = Country.Region %in% country_list)  # replace by %notin% if you want to exclude a country or list of them

# Readapt Data Set
df_selreg <- justSelReg %>%
  dplyr::group_by(date, type) %>%
  dplyr::summarise(total = sum(cases*sel_region, na.rm = TRUE)) %>%
  tidyr::pivot_wider(names_from = type,
                     values_from = total) %>%
  dplyr::arrange(date) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(active =  confirmed - death - recovered) %>%
  dplyr::mutate(confirmed_cum = cumsum(confirmed),
                death_cum = cumsum(death),
                recovered_cum = cumsum(recovered),
                active_cum = cumsum(active))
