### ISSUE TITLE
Changes in the structure of the data

### ISSUE THREAD

**Issue by RamiKrispin** [RamiKrispin/coronavirus#32]
As per changes in the raw data, as of March 23rd some major changes are taking places in the format of the data:

- The US data is now aggregated, the state and county-level data removed from this series
- The recovered cases were removed from the data

**Comment by gutama** [comment]
Hi Rami, what if we need recovered cases data for a country just like your dashboard
https://ramikrispin.github.io/coronavirus_dashboard/#summary

**Comment by shubhrampandey** [comment]
Can we extract from the daily reports instead of time series?

**Comment by emmecola** [comment]
What a pity! It was exciting to see the recovered variable eating up the confirmed cases in my stacked bar plots, as the outbreak comes to an end (e.g. in China). But I understand why they removed this information, too unreliable!

**Comment by RamiKrispin** [comment]
@gutama unfortunately as this data is no longer get updated, and therefore, I will have to remove it from the dashboard

**Comment by RamiKrispin** [comment]
@shubhrampandey I will check this option

**Comment by RamiKrispin** [comment]
@emmecola yes, I believe this and the challenge of collecting this data worldwide are the main reasons

**Comment by mmueller-cm** [comment]
@RamiKrispin to confirm - going forward, there will no longer be US state-level information; that is due to the source data set not including that information moving forward?

**Comment by gexijin** [comment]
Hi Rami, Could you keep U.S. state-level time-series data even if it is not updated?  
I would appreciate it if old data are kept and the data structure stays stable. 
Thanks for your hard work!

**Comment by balexturner** [comment]
> Hi Rami, Could you keep U.S. state-level time-series data even if it is not updated?
> I would appreciate it if old data are kept and the data structure stays stable.
> Thanks for your hard work!

This would be very helpful! Maybe a secondary data frame in the package with the non-updated US data.

**Comment by RamiKrispin** [comment]
@gexijin, @balexturner Yes I am working on adding the US state level to the package, probably as a separate dataset

**Comment by mmueller-cm** [comment]
@RamiKrispin Have you seen this attempt at aggregating state level data from the NYT? https://github.com/nytimes/covid-19-data

**Comment by RamiKrispin** [comment]
@mmueller-cm yes I saw it. I am currently examining few resources that I can use, will hopefully have the US states and counties level by Mon

**Comment by RamiKrispin** [comment]
Just to update recovered cases were back to the dataset
