### ISSUE TITLE
Recovered data

### ISSUE THREAD

**Issue by shubhrampandey** [RamiKrispin/coronavirus#33]
How we can get recovered data now????

As you see in my dashboard I have used recovered cases: https://shubhrampandey.shinyapps.io/coronaVirusViz

**Comment by RamiKrispin** [comment]
Sorry, for now, I don't have a solution as the data was removed from John Hopkins repo. I am looking for an alternative resource to pull this data, but given that John Hopkins decided to stop supply this data, I believe that this data is not easy to find

Nice dashboard!
