### ISSUE TITLE
Recovered + Active cases 

### ISSUE THREAD

**Issue by sotirismargaritis** [RamiKrispin/coronavirus#34]
How we can get except from recovered data and active cases?
There gonna be any changes at the coronavirus package including active and recovered columns?
Or is gonna be as it is?

**Comment by RamiKrispin** [comment]
The raw data that I am using to pull the data from, John Hopkins, stop publishing this data, so, unfortunately, this data is not available

**Comment by RamiKrispin** [comment]
@sotirismargaritis  recovered cases were added back to the raw data and now available on the Github version
