### ISSUE TITLE
Update_datasets is not pulling in "recovered" data?

### ISSUE THREAD

**Issue by KenneySnell** [RamiKrispin/coronavirus#35]
I just updated the data as of March 26 and there are no recovered cases.  Is that data missing or is in not available?  I see the data on the John Hopkins Coronavirus dashboard?

**Comment by RamiKrispin** [comment]
Recovered cases were removed from the John Hopkins raw data about a week ago. They added back two days ago, and I pushed it back to the package.

**Comment by KenneySnell** [comment]
Ravi

Thanks for all your good work on gathering the data.  The R code to produce high quality graphs takes time and it is frustrating when parts of the data are removed. I understand you have no control over what data is included in the source.  

I saw a post that said you were working on putting the US state data into a separate package / dataset. When will that be ready?

Will this updated US dataset be added to the update_datasets function?

Can you include the history data in the US dataset  back to January + Lat and Long data?   Is it possible to include county / city data in this dataset?

Thanks again

Kenney
