### ISSUE TITLE
Data structure Changes / dataset updates

### ISSUE THREAD

**Issue by KenneySnell** [RamiKrispin/coronavirus#38]
Rami:

Why are we having all these data changes? 

I can rationalize that the recovered case might be inaccurate and maybe hospitals are over burdened with saving patients, and not able to collect the data.

But I don't understand why the state and province data was removed.

1. Are you working on getting the state / province data back into the coronavirus dataset?
2. Will the county / city data be available with Lat / Long data?
3. Is there an issue with the daily updates to the datasets?  I had issues getting the data on the morning of March 29 (6 am EST [+ 4 GMT] )?

**Comment by RamiKrispin** [comment]
Hi Kenny,

The changes related to changes in the raw data itself. As for your questions:

1. The data was removed from the raw data, currently, there is a test version with county and state data for the US, working on adding it as a separate dataset in the package
2. The lat/long will be available for the US states and counties
3. No, it gets updated on a daily bases, unless there is a change in the structure of the data the required some code modifications
Best,
Rami
