### ISSUE TITLE
Covid-19

### ISSUE THREAD

**Issue by acgerstein** [RamiKrispin/coronavirus#4]
This looks great and I'm going to use this for a stats class I teach! There are a couple of places that say "Corvid 19" instead of Covid-19. Corvid is the family of birds that includes crows and ravens :-)

**Comment by RamiKrispin** [comment]
Thanks @acgerstein! 

I could not find those typo, could you please point out those places?

**Comment by acgerstein** [comment]
Apologies, it was from a page that linked to this (https://biol355.github.io/Labs/coronavirus.html). It's been corrected there now :-)

**Comment by RamiKrispin** [comment]
cool :)

More data detailed data is coming to the package in the coming days, hope you will find it useful
