### ISSUE TITLE
US Data by State and County

### ISSUE THREAD

**Issue by KenneySnell** [RamiKrispin/coronavirus#40]
1. What is the status on the US data and County information.?
2. What Package / Package location?
3.  Will the data be added to the coronavirus package or to another package?
4.  Will there be history information?
5.  I also want to build a US / state / County / City dashboard?  So I need Lat and Long data?

6. I see links to a package for US
a.
https://github.com/RamiKrispin/coronavirus/pull/22

install.packages("covid19us")
devtools::install_github("aedobbyn/covid19us")

b. Is this package a separate effort or are both  of you (Rami and  Author: Amanda Dobbyn) working on it together?

Thanks again for all the work you are doing.

Kenney

**Comment by RamiKrispin** [comment]
Hi Kenny, currently working on adding the US county-level data. There are some issues with the size of the data that surpass CRAN 5mb limitation. The plan is to have a designated package for each data source. The US data from John Hopkins will be under [covid19county](https://github.com/RamiKrispin/covid19county) package (work in progress). The data will have lat/long data and additional geospatial fields.

More US data, from different sources available on the covid19r project - https://github.com/Covid19R

**Comment by KenneySnell** [comment]
Rami

Thanks for the update. 

I have been looking at the John Hopkins CSSE site for US data.  

My plan is to use your site for World country data and the CSSE site for US state and county data. 

Keep me posted 

Kenney

**Comment by RamiKrispin** [comment]
For now, here is the package that supports US data based on the NY Times dataset:

https://github.com/Covid19R/covid19nytimes

The package is part of the [Covid19](https://github.com/Covid19R) project and it made by @jebyrnes 

Hope that helps.

Best,
Rami

**Comment by KenneySnell** [comment]
Rami

I’ll look at it 

Thanks for the update. 

Kenney

**Comment by KenneySnell** [comment]
Rami:

 

I originally built a Shiny App using John Hopkin CSSE data for US States only.

 

Then, I added US county data to the Shiny app.  Counties are listed for selection based on states selected.

 

https://kenneysnell.shinyapps.io/covid19_us_county/

 

Sincerely,

 

 

Kenney M. Snell

 

(502) 435-5272 Mobile

 <mailto:smk195333@gmail.com> smk195333@gmail.com

 

5402 Pueblo Road

Louisville, KY 40207

 <https://www.linkedin.com/in/kenney-snell-097812126/>

**Comment by RamiKrispin** [comment]
@KenneySnell  that is awesome!

You can add US maps using the following method:

https://covid19r.github.io/covid19nytimes/articles/county-maps.html

**Comment by jebyrnes** [comment]
I also recently learned about the albersusa package https://github.com/hrbrmstr/albersusa/ - get. All the states in one place!

On May 26, 2020, at 11:20 AM, Rami Krispin <notifications@github.com> wrote:

﻿
[EXTERNAL SENDER]

@KenneySnell<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKenneySnell&data=02%7C01%7Cjarrett.byrnes%40umb.edu%7C706bb0c8d2d445d6c4eb08d801886185%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637261032578728181&sdata=BKb5vMwbMQL%2FK0WjC1AXO1gCyY5ICmIFCNIOwwUU4fY%3D&reserved=0> that is awesome!

You can add US maps using the following method:

https://covid19r.github.io/covid19nytimes/articles/county-maps.html<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcovid19r.github.io%2Fcovid19nytimes%2Farticles%2Fcounty-maps.html&data=02%7C01%7Cjarrett.byrnes%40umb.edu%7C706bb0c8d2d445d6c4eb08d801886185%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637261032578728181&sdata=gec%2FZdq%2FplpVUGboJu75nJlA183k4tLkxXuvgIHyf20%3D&reserved=0>

**Comment by KenneySnell** [comment]
Rami:

 

Thanks for the update.  I am having trouble running my Shiny app with the county data now.  I guess the data is over 5mb limitation.

 

Sincerely,

 

Kenney

 

              I’ve added the US counties to the states in a new Shiny app.  

https://kenneysnell.shinyapps.io/covid19_us_county/

 

1.	Select county - In order to select a county, select the state for that county and check ‘Show county cases’.  Then find the county and select one or more.  There are 3200+ counties, so select a small number of states.  All the counties are shown for the states selected.

 

2.	Counts (cases) – Select either a state or county to list the counts per day.

 

 

Kenney M. Snell

 

(502) 435-5272 Mobile

 <mailto:smk195333@gmail.com> smk195333@gmail.com

 

 <https://www.linkedin.com/in/kenney-snell-097812126/>

**Comment by RamiKrispin** [comment]
Could you please provide a reproducible example (e.g., how you pull the data, and what are you getting, etc.)?

**Comment by KenneySnell** [comment]
Rami

I’ll send you my code and data source in a few days.  

Sincerely 
Kenney
