### ISSUE TITLE
Problem with update Dataset

### ISSUE THREAD

**Issue by sotirismargaritis** [RamiKrispin/coronavirus#42]
I cant update data for 10/4. I use update function and reinstalled from (devtools::install_github("RamiKrispin/coronavirus") but still nothing. 

Any idea?

Thanks

**Comment by olivermills** [comment]
Yea i'm having issues aswell

**Comment by Steno71** [comment]
Hello, same as above, I also tried to reinstall both through CRAN and through Github, in a clean session...
Thanks

**Comment by RamiKrispin** [comment]
Hi @sotirismargaritis, @olivermills , @Steno71, 

Yes, I am getting the same error, I think it related to migration of the current repo to a new [repo](https://github.com/Covid19R/coronavirus). See the reference on the readme file.  While both the current and the new repos are sync with the same updates, I believe that the URL reference is causing the error with devtools. You can either:
- install the package with the remotes package: `remotes::install_github("RamiKrispin/coronavirus", force = TRUE)`
- or install with **devtools** from the new repo: `devtools::install_github("covid19r/coronavirus")`

Either way, both repos are synchronized with the same data

**Comment by Steno71** [comment]
Works fine with this modification. Many thanks

**Comment by AntoineSoetewey** [comment]
> Hi @sotirismargaritis, @olivermills , @Steno71,
> 
> Yes, I am getting the same error, I think it related to migration of the current repo to a new [repo](https://github.com/Covid19R/coronavirus). See the reference on the readme file. While both the current and the new repos are sync with the same updates, I believe that the URL reference is causing the error with devtools. You can either:
> 
> * install the package with the remotes package: `remotes::install_github("RamiKrispin/coronavirus", force = TRUE)`
> * or install with **devtools** from the new repo: `devtools::install_github("covid19r/coronavirus")`
> 
> Either way, both repos are synchronized with the same data

Hi Rami,

Will the old repo stay in place (and be updated) or do you expect to gradually move from the old to the new repo?

Best,
Antoine

**Comment by RamiKrispin** [comment]
@AntoineSoetewey the old repo will stay in place and updated. The reference for the package is going to be on the new repo, which is part of a covid19R project:

https://github.com/Covid19R

**Comment by Steno71** [comment]
Hi,

Actually today it is not syncing again any further than 4/11. Tried both avenues described below...

Thanks

**Comment by NacheTyson** [comment]
Hello RamiKrispin, thank you for your contribution,
I'm from Bolivia I can't find province data, any suggestion. 
Tanks in advance

**Comment by olivermills** [comment]
@RamiKrispin has the data been updated for the 18th?

**Comment by RamiKrispin** [comment]
@Steno71 please provide a reproducible example (e.g, method used and output, etc.)

**Comment by miharbi1982** [comment]
Hi @RamiKrispin 
There's a problem with the update_datasets. What're new steps are we taking for that?
Note that a message error is :
"Skipping install of 'coronavirus' from a github remote, the SHA1 (39deae9c) has not changed since last install.
  Use `force = TRUE` to force installation
The data was refresed, please restart your session to have the new data available"
I restarting my session but no result.

**Comment by Steno71** [comment]
I was able to figure out that the problem was on my side.  Seems that Rstudio will not refresh data unless a new session is started. Deleting the variable and re-running the download script was not enough. Strange.

Anyway, thanks for your reply, I appreciate it

S

**Comment by olivermills** [comment]
Hi @RamiKrispin since yesterday I am getting the following error:
Error: 'update_datasets' is not an exported object from 'namespace:coronavirus'

I have tried re-installing the package using: remotes::install_github("RamiKrispin/coronavirus", force = TRUE)

But that doesn't seem to work.

Any ideas?

Appreciate all the work you put into this dataset :)

**Comment by RamiKrispin** [comment]
Sorry @olivermills for the late response, the function name was changed to `update_dataset` please install and retry again. Please let me know if you still have issues

**Comment by dtdibaba** [comment]
Hi RamiKrispin:

I notice that sometimes the coronavirus dataset is lagging behind that of worldometers by days. If you rely on worldometers to update the dataset, that would be the most reliable in my opinion.

For example, the data for May 16 is missing from coronavirus. You could easily import the data from worldometers once a day and update the repository. I am using the coronavirus for the dataset beyond two days and merge that to that of worldometers (which publish the data for today and a day before).
