### ISSUE TITLE
problem accessing the dataframe 

### ISSUE THREAD

**Issue by SagarS98** [RamiKrispin/coronavirus#43]
Hi! 
I am new to the analytics community and i used to use the R studio earlier now that i am using the jupyter notebook through the R environment and something unusual is happening which is when i print the data set it shows around 1500 rows only and the tasks i perform on the data set uses those 1500 rows only instead of the 64k rows
can you please help me out here 

Regards
Sagar 

![2](https://user-images.githubusercontent.com/63707151/79315953-4ff00600-7f21-11ea-9f22-4b7b8e73ee2f.PNG)
![3](https://user-images.githubusercontent.com/63707151/79315955-50889c80-7f21-11ea-97e2-24a917484ac6.PNG)

![1](https://user-images.githubusercontent.com/63707151/79315937-4d8dac00-7f21-11ea-987c-926d24f2a6e8.PNG)

**Comment by SagarS98** [comment]
its happening only when i try to open it the following way 
 
library(coronavirus)
data(coronavirus) 

and if i just read the csv through the basic read,csv command everything seems to work in order

**Comment by RamiKrispin** [comment]
Hi @SagarS98, I believe that you are using the CRAN version, which is updated up to Feb 16. The CRAN version is going to be updated in the coming days and will include a function that allows updating new data that comes after the CRAN release. 

For now, I recommend to install the Dev version using:
```
devtools::install_github("covid19r/coronavirus")
```

Best,
Rami
