### ISSUE TITLE
Problem with Dataset update

### ISSUE THREAD

**Issue by sotirismargaritis** [RamiKrispin/coronavirus#45]
Hello, i have a problem with the update of 18/4/20 data.  I cant update the data but in your dashboard and your repo it seems that you update the data yesterday.
 Any idea?
P.S I reinstalled the data from: devtools::install_github("covid19r/coronavirus") but still nothing

> coronavirus::update_datasets()
Updates are available on the coronavirus Dev version, do you want to update? n/YY
Skipping install of 'coronavirus' from a github remote, the SHA1 (f3a23ebe) has not changed since last install.
  Use `force = TRUE` to force installation
The data was refresed, please restart your session to have the new data available

**Comment by RamiKrispin** [comment]
Thanks @sotirismargaritis ,

I think that the issue you related to a gap between the dev version and the csv version that the `update_datasets()` function is using as a reference. I am going to update the reference and the script that run it to avoid this type of error in the future.

**Comment by AntoineSoetewey** [comment]
Dear @RamiKrispin,

I tried to update the dataset as well, but the latest data is still April 18.
Here is what I did:
* `devtools::install_github("RamiKrispin/coronavirus", force = TRUE)`
* `update_datasets()`
* `devtools::install_github("covid19r/coronavirus", force = TRUE)`

None of the 3 alternatives work.

Best,
Antoine

**Comment by AntoineSoetewey** [comment]
> Dear @RamiKrispin,
> 
> I tried to update the dataset as well, but the latest data is still April 18.
> Here is what I did:
> 
> * `devtools::install_github("RamiKrispin/coronavirus", force = TRUE)`
> * `update_datasets()`
> * `devtools::install_github("covid19r/coronavirus", force = TRUE)`
> 
> None of the 3 alternatives works.
> 
> Best,
> Antoine

Issue fixed, thanks!
