### ISSUE TITLE
Dataset Issue

### ISSUE THREAD

**Issue by Dessiii** [RamiKrispin/coronavirus#46]
Hello, thanks a lot for the resources. At some points, the number of cases is negative (<0). Is that fine? Does it have any specific meaning? Or is this an error? Find some in the screenshot below:
![Capture](https://user-images.githubusercontent.com/63981380/79701050-144f9600-82ab-11ea-8bd1-ba44bfd04574.PNG)

**Comment by RamiKrispin** [comment]
Hi @Dessiii, 

Negative values are results of either an error on the raw data or retroactive update of past data (e.g., false positive, new information, etc.). 

Please see the following [issue](https://github.com/RamiKrispin/coronavirus/issues/15) or this [issue](https://github.com/RamiKrispin/coronavirus/issues/5)

**Comment by Dessiii** [comment]
Hi Rami, do you think I can set all negative values to 0? For the analysis I am planning on doing, I need all the values should be >=0. What manipulations do you suggest?

**Comment by RamiKrispin** [comment]
It really depends on the number of cases that are negative and the model that you are using.
