### ISSUE TITLE
Negative case values

### ISSUE THREAD

**Issue by j4yr0u93** [RamiKrispin/coronavirus#5]
Is there a significance to negative case values? Or is it a bug? I didn't see anything in the introduction about it.

**Comment by RamiKrispin** [comment]
Thanks for bringing it up. I checked and those cases are on the original time series data that I am pulling from John Hopkins repo. I suspect that it related to either updating false-positive cases or error in the counting. I opened an [issue](https://github.com/CSSEGISandData/COVID-19/issues/285) and I will update those cases according to their answer

**Comment by RamiKrispin** [comment]
Here is the response on the issue I opened on John Hopkins (CSSEGISandData repo):

"We have noted this discrepancy in the data and have concluded that these values were reported correctly from our sources. There may be reports that change over time as new requirements in reporting evolve. These values in our data are the result of the changes in reporting."

Therefore, for now, I treat the CSSEGISandData repo as the source of truth.
