### ISSUE TITLE
Dataset lagging behind other sources

### ISSUE THREAD

**Issue by dtdibaba** [RamiKrispin/coronavirus#51]
Hi Rami Krispin:

I notice that sometimes the coronavirus dataset is lagging behind that of worldometers by days. If you rely on worldometers to update the dataset, that would be the most reliable in my opinion.

For example, the data for May 16 is missing from coronavirus. You could easily import the data from worldometers once a day and update the repository. I am using the coronavirus for the dataset beyond two days and merge that to that of worldometers (which publish the data for today and a day before).

**Comment by RamiKrispin** [comment]
Yes, I just noticed that the cron job was off. It should be refresh in the coming hours

**Comment by dtdibaba** [comment]
Thanks, I will check it.
