### ISSUE TITLE
Latest data as of 25th of May is from 14th of May

### ISSUE THREAD

**Issue by davelorino** [RamiKrispin/coronavirus#53]
Hi, the latest data accessible through this library is over ten days old - is this intentional?

Thank you,

**Comment by Nilafhiosagam** [comment]
I think the link to the data was updated. I was pulling from: https://raw.githubusercontent.com/RamiKrispin/coronavirus-csv/master/coronavirus_dataset.csv

But now from: https://raw.githubusercontent.com/RamiKrispin/coronavirus/master/csv/coronavirus.csv

**Comment by RamiKrispin** [comment]
Hi @davelorino 

The data is updated on a daily bases, and as for today, the most recent data available on the package is from yesterday (May 25th). If you installed the most recent CRAN version (v0.2.0) you should have upon installation data from May 12th. To update the data you should use the `update_dataset()` function, which will pull the most recent data available on the Github repo of the package.

More information about updating the data available over here:
https://ramikrispin.github.io/coronavirus/articles/update_dataset_function.html

If you want to use the csv version, as @Nilafhiosagam mentioned, it is available on the csv folder here:
https://raw.githubusercontent.com/RamiKrispin/coronavirus/master/csv/coronavirus.csv

Please let me know if this works (or not).

Best,
Rami

**Comment by davelorino** [comment]
Hi, yeah the link where the data is accessed from changed in place, thanks
you to the user who pointed this out.
