### ISSUE TITLE
Total number of recovered cases negative

### ISSUE THREAD

**Issue by niroshar** [RamiKrispin/coronavirus#55]
It seems that there are negative numbers for total number of recovered. Ex:

![Covid_US](https://user-images.githubusercontent.com/15957869/85855740-5d750800-b77c-11ea-818c-9ece770f1ef6.PNG)

**Comment by RamiKrispin** [comment]
The `coronavirus` dataset calculates the daily new cases (confirmed, recovered, death) by taking the delta of each day with the previous one. Therefore, negative cases could occur when there is a drop in the cumulative number of cases with respect to the previous day. This so far occurred when:

- There is a change in the counting methodology or data resource (for example this [issue](https://github.com/RamiKrispin/coronavirus/issues/52) and this [one](https://github.com/CSSEGISandData/COVID-19/issues/2522))
- Updating new cases (or removing false-positive cases) not on the day that they were count
- Errors in the raw data

For the US, in the raw data, the total cumulative number of recover cases on May 11 was 230287, where on the following day it dropped to 232733, which reflect a daily change of -2446 cases.

**Comment by Siddhant-K-code** [comment]
is there any way to fix this ? like using absolute value to print?

**Comment by RamiKrispin** [comment]
I think using absolute value would be misleading as those cases are being removed from the count
