### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by alexbrillant** [RamiKrispin/coronavirus#56]
Hello, I was wondering if you were thinking about putting a license on this dataset. Can I use it for my own open source project ?

**Comment by RamiKrispin** [comment]
Hi @alexbrillant the package is already under [MIT license](https://github.com/RamiKrispin/coronavirus/blob/master/LICENSE.md), you are more than welcome to use it on your own open-source project. You need to take into account the source of the data is coming from external sources (see the list on the button of the readme).

**Comment by alexbrillant** [comment]
Awesome thanks ! I couldn't find it on this repo. I think you should add the license in this MIT repo as well, because I think that without any license it means that I cannot necessearily use it.

**Comment by RamiKrispin** [comment]
You welcome! you can find the package license on the [Description](https://github.com/RamiKrispin/coronavirus/blob/dc25a163d024a4785ee8868183ad722cad5b655b/DESCRIPTION#L15) file of the package and in the package [READM](https://github.com/RamiKrispin/coronavirus/blob/master/README.md) file
