### ISSUE TITLE
Total number of infected cases in Spain on 24.04.2020 is negative

### ISSUE THREAD

**Issue by GithubSom** [RamiKrispin/coronavirus#58]
Hi,
Thank you for your excellent work.
I noticed one error for the dataset of Spain. **On 24.04.2020 and 25.05.2020 the total number of COVID-19 infected cases are negative.**

Can you please have a look.
Thanks,
Som

**Comment by RamiKrispin** [comment]
Hi @GithubSom, 

Negative values will occur in the data whenever there is a drop in the cumulative values in the source data of John Hopkins. This could occur when the source data is changing, errors, updates and fix on the data, etc. The negative cases on Spain during Apr 24th are related to changes in the reporting system in Spain, more details available on the following [issue](https://github.com/CSSEGISandData/COVID-19/issues/2522).

Best,
Rami

**Comment by GithubSom** [comment]
Thanks for the clarification.
Thanks again for the excellent work.

Best,
Som
