### ISSUE TITLE
Update package locally

### ISSUE THREAD

**Issue by shubhrampandey** [RamiKrispin/coronavirus#6]
Hi,

I am seeing that you have updated data on the github but that didn't update in my local computer however I have used:

if (!require(coronavirus)) {devtools::install_github("RamiKrispin/coronavirus",upgrade = "always"); library(coronavirus)}

Please help me out.

**Comment by RamiKrispin** [comment]
I think that it won't work if you have old version installed, then `!require(coronavirus)` will return FALSE and it won't run the installation command

**Comment by GShotwell** [comment]
You should just be able to call `devtools::install_github()`(i.e. no need for the `require`), it will only update if there have been new commits to master.
