### ISSUE TITLE
The csv file contains git info rows

### ISSUE THREAD

**Issue by aleixdorca** [RamiKrispin/coronavirus#66]
For the last couple of days the refresh_coronavirus_jhu() function has been giving me problems.

After executing the commands manually I have seen that the CSV contains the following rows:

```
<<<<<<< HEAD
=======
...
>>>>>>> master
```
As well as some other git information.

Of course, this breaks the CSV parsing.

**Comment by RamiKrispin** [comment]
Thanks @aleixdorca, pushed an update, that should work now, please check and let me know if you still have issues with that

**Comment by aleixdorca** [comment]
Thanks a lot! It is now working as expected.
