### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by LiXingguangBrandonStark** [RamiKrispin/coronavirus#67]
could you please plot the data in the map, this will be more helpful, thanks.

**Comment by RamiKrispin** [comment]
Hi @LiXingguangBrandonStark,

You have an example for a map on the following dashboard:
https://ramikrispin.github.io/coronavirus_dashboard/

![image](https://user-images.githubusercontent.com/12760966/105451439-6c983780-5c31-11eb-9dce-cb7632ee9c27.png)

You can see the code behind the map here:
https://github.com/RamiKrispin/coronavirus_dashboard/blob/33f45de4ddc39995ebc137f326c3b37149a2a19b/index.Rmd#L237

**Comment by LiXingguangBrandonStark** [comment]
Thanks. You are so nice.

**Comment by LiXingguangBrandonStark** [comment]
Could you please make the Taiwan into China search, thanks.

**Comment by RamiKrispin** [comment]
I am currently using the John Hopkins country/state definition

**Comment by LiXingguangBrandonStark** [comment]
got it.
