### ISSUE TITLE
Version 0.3.2 breaks refresh_coronavirus_jhu()

### ISSUE THREAD

**Issue by aleixdorca** [RamiKrispin/coronavirus#69]
Rami,

I've just updated to version 0.3.2 and it seems that the refresh_coronavirus_jhu() function does not work properly. Going a bit deeper into the issue I've seen that the location (and also location_type) column is created with this ifelse call:

`df$location <- ifelse(df$province == "", df$country, paste(df$province, df$country, sep = ", "))`

The problem seems to be that the province column does not have empty values but NA values. This may be new or something on my system... Either case I've fixed it changing the call to this:

```
df$location <- ifelse((df$province == "" | is.na(df$province)), df$country, paste(df$province, df$country, sep = ", "))
df$location_type <- ifelse(df$province == "" | is.na(df$province), "country", "state")
```

Hope it helps.

**Comment by RamiKrispin** [comment]
Hi @aleixdorca,

Thanks for the feedback. I replaced the `read.csv` function with `read_csv` from the **readr** that by default replaced empty strings with `NA`s. I just pushed a fix for the `refresh_coronavirus_jhu` function, could please try to install the package from Github (`devtools::install_github("RamiKrispin/coronavirus")`) and please let me know if it is working properly? 

Thanks,
Rami

**Comment by aleixdorca** [comment]
All back to normal.

Thanks, Rami.
