### ISSUE TITLE
Negative values were found in the package

### ISSUE THREAD

**Issue by ddong63** [RamiKrispin/coronavirus#7]
This package is really cool! Thanks for putting them together! 

I found some negative values in this package. I checked the raw data source, and didn't see negative values there. I guess some errors might be introduced during the data processing? 

```
> library(coronavirus)
> data("coronavirus")
> coronavirus %>% arrange(cases) %>% head(20)
# A tibble: 20 x 7
   Province.State                         Country.Region   Lat   Long date       cases type     
   <chr>                                  <chr>          <dbl>  <dbl> <date>     <int> <chr>    
 1 "Omaha, NE (From Diamond Princess)"    US              41.3  -96.0 2020-02-24   -11 confirmed
 2 "Diamond Princess cruise ship"         Others          35.4  140.  2020-03-06   -10 confirmed
 3 "From Diamond Princess"                Australia       35.4  140.  2020-02-29    -8 confirmed
 4 "Travis, CA (From Diamond Princess)"   US              38.3 -122.  2020-02-24    -5 confirmed
 5 "New York County, NY"                  US              40.7  -74.0 2020-03-07    -5 confirmed
 6 "Hainan"                               Mainland China  19.2  110.  2020-02-15    -4 recovered
 7 "Guizhou"                              Mainland China  26.8  107.  2020-02-06    -3 recovered
 8 "Ningxia"                              Mainland China  37.3  106.  2020-02-09    -2 recovered
 9 "Heilongjiang"                         Mainland China  47.9  128.  2020-02-11    -2 recovered
10 "Lackland, TX (From Diamond Princess)" US              29.4  -98.6 2020-02-24    -2 confirmed
11 ""                                     Japan           36    138   2020-01-23    -1 confirmed
12 "Queensland"                           Australia      -28.0  153.  2020-01-31    -1 confirmed
13 "Queensland"                           Australia      -28.0  153.  2020-02-02    -1 confirmed
14 "Shanxi"                               Mainland China  37.6  112.  2020-02-03    -1 recovered
15 "Guangxi"                              Mainland China  23.8  109.  2020-02-12    -1 recovered
16 "Hong Kong"                            Hong Kong       22.3  114.  2020-02-21    -1 recovered
17 "Diamond Princess cruise ship"         Others          35.4  140.  2020-02-23    -1 recovered
18 ""                                     Italy           43     12   2020-02-24    -1 recovered
19 "Northern Territory"                   Australia      -12.5  131.  2020-03-06    -1 confirmed
20 ""                                     South Korea     36    128   2020-01-22     1 confirmed
```

**Comment by RamiKrispin** [comment]
Hi @ddong63, thanks for the feedback. The reasons for the negative values are either related to either typo on the raw data or reclassification of the cases ("From Diamond Princess" cases). I already fixed the cases related to typo (see this [issue](https://github.com/CSSEGISandData/COVID-19/issues/285)) and working on update the Diamond Princess cases reclassification. 

The reason that you are not seeing negative values on the raw data, is that it is cumulative as opposed to daily new cases (which is the diff of the first).  Therefore, in the raw data for those cases above, you will see a drop in the cumulative value in the following day.

Hope that makes sense,
Rami

**Comment by ddong63** [comment]
> The reason that you are not seeing negative values on the raw data, is that it is cumulative as opposed to daily new cases (which is the diff of the first). Therefore, in the raw data for those cases above, you will see a drop in the cumulative value in the following day.

Gotcha! That makes some sense. If it is cumulative, I understand cases when there is a drop in `confirmed`, because they could be recovered or dead. However, I still have hard time understand why there is a drop in `recovered` cases. Should they be always increasing? 

If we see a decline in `recovered` cases, that means, someone was recovered, and got infected again or dead on the second day? What do you think?

**Comment by RamiKrispin** [comment]
@ddong63 NO, there should not be a drop in any of the types, all cumulative, including the confirmed. Recovered cases are not removed from confirmed cases. So far, the reasons for the drops are typos and reclassification of cases from the Diamond Princess cases.

**Comment by piccolbo** [comment]
Are you saying that the number of new cases is computed backwards from a difference of confirmed cases and when confirmed cases drops because of a reclassification, you can have negative cases? That would explain errors in my log-scale analysis. Thanks for your work on this.

**Comment by RamiKrispin** [comment]
@piccolbo yes, daily new cases are the delta of the cumulative cases.

**Comment by ddong63** [comment]
This is helpful. Thanks for clarifying this! @RamiKrispin

**Comment by RamiKrispin** [comment]
Here is the response on the issue I opened on John Hopkins (CSSEGISandData repo):

"We have noted this discrepancy in the data and have concluded that these values were reported correctly from our sources. There may be reports that change over time as new requirements in reporting evolve. These values in our data are the result of the changes in reporting."

Therefore, for now, I treat the CSSEGISandData repo as the source of truth.
