### ISSUE TITLE
Data not up to date

### ISSUE THREAD

**Issue by stepminer** [RamiKrispin/coronavirus#70]
The raw data pulled from the Johns Hopkins University Center for Systems Science and Engineering (JHU CCSE) Coronavirus repository at 4:00 AM may not be up to date as the JHU CCSE updates the data more frequently.

Can Rami Krispin set the auto-update let's say twice daily instead of once?

Thanks

p.s

**Comment by RamiKrispin** [comment]
Hi @stepminer,

The data is refreshed on a daily basis, here is how you can get the most recent data:
```
> df <- coronavirus::refresh_coronavirus_jhu()
Parsed with column specification:
cols(
  date = col_date(format = ""),
  province = col_character(),
  country = col_character(),
  lat = col_double(),
  long = col_double(),
  type = col_character(),
  cases = col_double()
)
|=====================================| 100%   16 MB
Parsed with column specification:
cols(
  location = col_character(),
  location_code = col_character(),
  location_code_type = col_character()
)
> max(df$date)
[1] "2021-01-28"
```

Please let me know if you have any issue pulling the data.

Rami

**Comment by stepminer** [comment]
*Greetings Rami,*

*Thanks for following up and the code to pull the data from JHU.
Unfortunately, I ran into the following error and the data was not
refreshed when I run the codes provided:*

*Error: unexpected symbol in "Parsed with" *

> df <- coronavirus::refresh_coronavirus_jhu()
Parsed with column specification:
cols(
  date = col_date(format = ""),
  province = col_character(),
  country = col_character(),
  lat = col_double(),
  long = col_double(),
  type = col_character(),
  cases = col_double()
)
Parsed with column specification:
cols(
  location = col_character(),
  location_code = col_character(),
  location_code_type = col_character()
)
> Parsed with column specification:
Error: unexpected symbol in "Parsed with"
>     cols(
+         date = col_date(format = ""),
+         province = col_character(),
+         country = col_character(),
+         lat = col_double(),
+         long = col_double(),
+         type = col_character(),
+         cases = col_double()
+     )
cols(
  date = col_date(format = ""),
  province = col_character(),
  country = col_character(),
  lat = col_double(),
  long = col_double(),
  type = col_character(),
  cases = col_double()
)
>
> Parsed with column specification:
*Error: unexpected symbol in "Parsed with"*
>     cols(
+         location = col_character(),
+         location_code = col_character(),
+         location_code_type = col_character()
+     )
cols(
  location = col_character(),
  location_code = col_character(),
  location_code_type = col_character()
)
> max(df$date)
[1] "2021-01-29"

*Do you have an idea why I am getting this error? I did load the library
(tidyverse) before running the codes.*

*Thanks again, your help is appreciated,*

*Patrick Stephenson*

**Comment by RamiKrispin** [comment]
What version are you using? Can you please run `packageVersion("coronavirus")`?

**Comment by stepminer** [comment]
Here it is:

> packageVersion("coronavirus")
[1] ‘0.3.21’

**Comment by RamiKrispin** [comment]
What is the output you are receiving for the following?
``` r
packageVersion("reader")
```
and
```
df <- readr::read_csv("https://raw.githubusercontent.com/RamiKrispin/coronavirus/master/csv/coronavirus.csv")
```

**Comment by stepminer** [comment]
Greetings Rami,

The output is successful. Great work congrats.

Pat
===========================
> packageVersion("reader")
[1] ‘1.0.6’
>
> df <- readr::read_csv("
https://raw.githubusercontent.com/RamiKrispin/coronavirus/master/csv/coronavirus.csv
")
Parsed with column specification:
cols(
  date = col_date(format = ""),
  province = col_character(),
  country = col_character(),
  lat = col_double(),
  long = col_double(),
  type = col_character(),
  cases = col_double()
)
|=======================================================================|
100%   16 MB

**Comment by RamiKrispin** [comment]
Could you please check if you are running the code in this [function](https://github.com/RamiKrispin/coronavirus/blob/b061e5c859522762a10dd337a4455412594435ee/R/refresh_coronvirus.R#L25) and see if you are getting any error?

Also, it might be related to the version of the **readr** package (I am using v1.3.1)

**Comment by stepminer** [comment]
Hello Rami,

The function seems to run Fine. However, I am not sure the df was updated.
A data frame of 17 MB was apparently downloaded in record time but the data
is still as of "2021-02-12".

Best,

Pat

**Comment by RamiKrispin** [comment]
Typically the data is one or two days behind, for example, today (Feb 15):

``` r
> df <- coronavirus::refresh_coronavirus_jhu()
Parsed with column specification:
cols(
  date = col_date(format = ""),
  province = col_character(),
  country = col_character(),
  lat = col_double(),
  long = col_double(),
  type = col_character(),
  cases = col_double()
)
Parsed with column specification:
cols(
  location = col_character(),
  location_code = col_character(),
  location_code_type = col_character()
)
> max(df$date)
[1] "2021-02-14"
```

**Comment by glaswasser** [comment]
Hi, I'm trying to build up a R shiny dashboard which automatically updates the data each time it is loaded, but the update_dataset() command doesn't seem to work once the shiny is deployed. Do you have a suggestion to solve this? Thanks and sorry for my beginner question ;)

**Comment by RamiKrispin** [comment]
@glaswasser do you mind open a new issue with more details (session info, etc)?

**Comment by glaswasser** [comment]
@RamiKrispin 
Thanks for the quick reply, there was no error, the issue was only that the data was not up to date anymore despite using the update_dataset() command inside an R shiny web-app - I think I solved it now by merely using the command instead:

`read.csv("https://raw.githubusercontent.com/RamiKrispin/coronavirus/master/csv/coronavirus.csv", stringsAsFactors = FALSE)`

**Comment by RamiKrispin** [comment]
I would say that probably the package is not installed in the env you are running the shiny app
