### ISSUE TITLE
update_dataset() throws error since today

### ISSUE THREAD

**Issue by ondohotola** [RamiKrispin/coronavirus#81]
I run 

R version 4.1.1 (2021-08-10) -- "Kick Things"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin20.4.0 (64-bit)

daily updated with update.packages()

Since this morning I see this error when running 

update_dataset()

Rows: 483336 Columns: 7                                                                                                                                
 0s── Column specification ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr  (3): province, country, type
dbl  (3): lat, long, cases
date (1): date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Downloading GitHub repo RamiKrispin/coronavirus@master
✓  checking for file ‘/private/var/folders/t6/7hrkm43x3f1fd_f1wq0_w1pm0000gr/T/Rtmp8WWa7c/remotesa88732872e85/RamiKrispin-coronavirus-fc0b220/DESCRIPTION’ ...
─  preparing ‘coronavirus’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘coronavirus_0.3.23.tar.gz’
   
Installing package into ‘/usr/local/lib/R/4.1/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘coronavirus’ ...
** using staged installation
** R
Error in parse(outFile) : 
  /private/var/folders/t6/7hrkm43x3f1fd_f1wq0_w1pm0000gr/T/Rtmp4UDCbq/R.INSTALLae017d866135/coronavirus/R/refresh_coronvirus.R:26:1: unexpected input
25:   df <- NULL
26: <<
    ^
ERROR: unable to collate and parse R files for package ‘coronavirus’
* removing ‘/usr/local/lib/R/4.1/site-library/coronavirus’
* restoring previous ‘/usr/local/lib/R/4.1/site-library/coronavirus’
Caught an warning!
<simpleWarning in i.p(...): installation of package ‘/var/folders/t6/7hrkm43x3f1fd_f1wq0_w1pm0000gr/T//Rtmp8WWa7c/filea88748ff37ad/coronavirus_0.3.23.tar.gz’ had non-zero exit status>

**Comment by stepminer** [comment]
I have the same issue. The update would not work as usual. 
Error in parse(outFile) : 
  C:/Users/stepm/AppData/Local/Temp/Rtmp6HSBSc/R.INSTALL1f9060b63f3/coronavirus/R/refresh_coronvirus.R:26:1: unexpected input
25:   df <- NULL
26: <<
    ^
ERROR: unable to collate and parse R files for package 'coronavirus'
* removing 'C:/Users/stepm/Documents/R/win-library/4.0/coronavirus'
* restoring previous 'C:/Users/stepm/Documents/R/win-library/4.0/coronavirus'
installation of package �C:/Users/stepm/AppData/Local/Temp/RtmpkhG4ej/file211c7f9734b1/coronavirus_0.3.3.tar.gz� had non-zero exit status

**Comment by ondohotola** [comment]
Using the

	refresh_coronavirus_jhu()

function works however.

Required changes to my code (but with mutate() not much drama).

Just a little niggle that NA is missing value and 'NA' ISO code for
Namibia, but also quite easy to fix:

	 corona = as_tibble(refresh_coronavirus_jhu()) %>%
		  mutate(location_code = case_when(location == 'Namibia' ~ 'NA'))

greetings, el


On 02/09/2021 11:22, stepminer wrote:
> I have the same issue. The update would not work as usual.
> Error in parse(outFile) :
> C:/Users/stepm/AppData/Local/Temp/Rtmp6HSBSc/R.INSTALL1f9060b63f3/coronavirus/R/refresh_coronvirus.R:26:1: unexpected input
> 25: df <- NULL
> 26: <<
> ^
> ERROR: unable to collate and parse R files for package 'coronavirus'
[...]

-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply
	  Book your Covid-10 Vaccination at https://c19.idtoday.com.na

**Comment by stepminer** [comment]
Thanks, but the local coronavirus file did not seem to have updated, I am getting the August 31 results for my Dashboard.
Although the JHU update seems to work. Should I also change my codes for the Dashboard?
> df <- coronavirus::refresh_coronavirus_jhu()
Parsed with column specification:
cols(
  date = col_date(format = ""),
  province = col_character(),
  country = col_character(),
  lat = col_double(),
  long = col_double(),
  type = col_character(),
  cases = col_double()
)
Parsed with column specification:
cols(
  location = col_character(),
  location_code = col_character(),
  location_code_type = col_character()
)
> max(df$date)
[1] "2021-09-01"

**Comment by RamiKrispin** [comment]
Hi @ondohotola @stepminer,
There was an error with branches merging that cause this issue, which, hopefully, should work now. I going to push to cran on the coming weekend some of the recent changes with the data so I would recommend until then installing the dev version:
```
devtools::install_github("RamiKrispin/coronavirus")
````

Please let me know if you still have issues pulling the data.

**Comment by ondohotola** [comment]
Rami,

thank you,

that does it for me :-)-O

Thank you, el

**Comment by stepminer** [comment]
Thanks, Rami,

congrats .

Pat

**Comment by ondohotola** [comment]
Rami,

I am getting these error today:

	 Downloading GitHub repo ***@***.***
	 Error in utils::download.file(url, path, method = method, quiet = quiet,  :
		download from 'https://api.github.com/repos/RamiKrispin/coronavirus/tarball/HEAD' failed

The dataset on CRAN is still from May and when I answer Y to the request
for development update I get the same errorL

	 Downloading GitHub repo ***@***.***
	 Error in utils::download.file(url, path, method = method, quiet = quiet,  :
		download from 'https://api.github.com/repos/RamiKrispin/coronavirus/tarball/master' failed


greetings, el

-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply
	  Book your Covid-10 Vaccination at https://c19.idtoday.com.na

**Comment by RamiKrispin** [comment]
I am not sure why you are getting this error, works on my end. I would recommend doing the following:

- Reset the session and try to run the `update_dataset()` function
- If not working try to install latest version from Github:
```
devtools::install_github("RamiKrispin/coronavirus")
```

**Comment by ondohotola** [comment]
Resolved spontaneously :-)-O

Could be the propagation to the nearest CDN host, so maybe I'll wait some more in the future :-)-O

Thank you,

el

**Comment by RamiKrispin** [comment]
new version (0.3.30) with fixes for the `update_dataset` function is now on CRAN, please let me know if you have any issues.

**Comment by ondohotola** [comment]
Thanks,

data is still only up to 2021-05-27



On 2021-09-19 15:55 , Rami Krispin wrote:
> new version (0.3.30) with fixes for the |update_dataset| function is
> now on CRAN, please let me know if you have any issues.
[...]


-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply
	 Book your Covid-10 Vaccination at https://c19.idtoday.com.na

**Comment by ondohotola** [comment]
Maybe I was too hasty :-)-O

After a restart it works right. So issue between screen and chair :-)-O

el

On 2021-09-19 18:52 , Dr Eberhard W Lisse wrote:
> Thanks,
> 
> data is still only up to 2021-05-27
> 
> 
> 
> On 2021-09-19 15:55 , Rami Krispin wrote:
>> new version (0.3.30) with fixes for the |update_dataset| function is
>> now on CRAN, please let me know if you have any issues.
> [...]
> 
> 


-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply
      Book your Covid-10 Vaccination at https://c19.idtoday.com.na

**Comment by RamiKrispin** [comment]
Great! 

Please make sure you have the most recent version from CRAN:
```
packageVersion("coronavirus")
[1] ‘0.3.30’
```

**Comment by ondohotola** [comment]
Thank you,

as I wrote it was an issue between screen and chair.

greetings, el
On 2021-09-19 20:17 , Rami Krispin wrote:
> Great!
> 
> Please make sure you have the most recent version from CRAN:
> 
> |packageVersion("coronavirus") [1] ‘0.3.30’ |


-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply
      Book your Covid-10 Vaccination at https://c19.idtoday.com.na
