### ISSUE TITLE
How do u make it realtime and auto update 

### ISSUE THREAD

**Issue by navmedvideos** [RamiKrispin/coronavirus#9]
Hey mate, thanks for a great package, can't figure out how to make it auto-updating and real-time?

I would like to use it here - 

[LIVE] Coronavirus: Real-Time Counter, World Map, News - Come hangout and chat - 24x7 live

https://www.youtube.com/watch?v=i9rVyLr00Ck

**Comment by RamiKrispin** [comment]
Thanks @navmedvideos, this is really cool channel!

I am working on automating the package data stream, will be hopefully available next week.

**Comment by lgellis** [comment]
Hi @RamiKrispin again great pkg!!! 

Just to ensure I'm not missing the obvious - it seems it's expected behavior that as of today it would have March 2 as the latest update (b/c you're working on auto-updates) right?  

Thanks again and GREAT work on this!  :+1: :star:

**Comment by jebyrnes** [comment]
In the meantime, in the dev-jebyrnes branch, there's an `update_data_raw()` function that will pull in new data. @RamiKrispin could change this quite a bit for the master branch, but, as a stopgap, it works - although beware the data is not QC-ed.

**Comment by RamiKrispin** [comment]
Package now update daily automatically with a cron job
