### ISSUE TITLE
Error 404 in refresh_coronavirus_jhu()

### ISSUE THREAD

**Issue by aleixdorca** [RamiKrispin/coronavirus#96]
Part of the data is not downloaded, in particular: https://github.com/RamiKrispin/coronavirus/raw/dev-covid19r/data_raw/iso_3166_2_code_table.csv -> Error 404.

**Comment by RamiKrispin** [comment]
Thanks, fixed the issue, could you please check if it is working now?

**Comment by aleixdorca** [comment]
Thanks, Rami, it is working as expected now!
